# Configuration for behaviorbot - https://github.com/behaviorbot/

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for helping us improve and opening your first issue here! Someone will address it right away!

newPRWelcomeComment: >
  I can tell this is your first pull request! Thank you I'm so honored. :tada::tada::tada:

  I'll take a look at it ASAP!

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Your code looks great! Congrats, I've gone ahead and merged your first pull request! Keep it up!

  ![alt text](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif "WOOHOO")
